---
apiVersion: v1
kind: Namespace
metadata:
  name: kuard-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard-deployment
  namespace: telstra-demo
  labels:
    app: kuard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:1
          name: kuard
          ports:
            - containerPort: 8080
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: kuard-service
  namespace: telstra-demo
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31880
      name: kuard-service
  selector:
    app: kuard

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kuard-route
  namespace: telstra-demo
spec:
  host: kuard-route-telstra-demo.apps.mgm2.tmetse.bos2.lab
  port:
    targetPort: kuard-service
  to:
    kind: Service
    name: kuard-service
    weight: 100
  wildcardPolicy: None
